{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tenant-website.fullname" . }}
  labels:
    {{- include "tenant-website.labels" . | nindent 4 }}
    release: monitoring
spec:
  selector:
    matchLabels:
      {{- include "tenant-website.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
{{- end }}
